--MAGNITUDE

--Find total customers by country
SELECT country, COUNT(customer_key) AS Nr_of_Customers
FROM gold.dim_customers
GROUP BY country
ORDER BY Nr_of_Customers DESC

--Find total customers by gender
SELECT gender, COUNT(customer_key) AS Nr_of_Customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY Nr_of_Customers DESC

--Find total products by category
SELECT category, COUNT(product_key) AS Nr_of_Products
FROM gold.dim_products
GROUP BY category
ORDER BY category DESC

--What is the average costs in each category?
SELECT category, AVG(product_cost) AS Average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY Average_cost DESC

--what is the total revenue generated for each category?
SELECT category, SUM(sales_amount) AS TotalRevenue
FROM gold.fact_sales fc
LEFT JOIN gold.dim_products dp ON fc.product_key = dp.product_key
GROUP BY category
ORDER BY TotalRevenue DESC

--Find total revenue generated by each customer
SELECT fs.customer_key, dc.first_name, dc.last_name ,SUM(sales_amount) AS TotalRevenue
FROM gold.fact_sales fs
LEFT JOIN gold.dim_customers dc ON fs.customer_key = dc.customer_key
GROUP BY fs.customer_key, dc.first_name, dc.last_name
ORDER BY TotalRevenue DESC

--What is the distribution of sold items across countries?
SELECT dc.country,SUM(quantity) AS Total_sold_items
FROM gold.fact_sales fs
LEFT JOIN gold.dim_customers dc ON fs.customer_key = dc.customer_key
GROUP BY dc.country
ORDER BY Total_sold_items DESC
